# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print(np.__version__)
print(np.show_config())

2.2.3
{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.0.12",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.29.30158",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.28",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-3gfa2f0z/cp311-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib 

c:\Users\96655\AppData\Local\Programs\Python\Python311\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
a=np.random.rand(2,3,5)

''' the first way
a=np.random.randn(2,3,5)
print(a)tow way
a=np.random.randint(0,50,(2,3,5))
print(a)'''

' the first way\na=np.random.randn(2,3,5)\nprint(a)tow way\na=np.random.randint(0,50,(2,3,5))\nprint(a)'


### 4. Print a.


In [4]:
### [your code here]
print(a)


[[[0.68495333 0.92562567 0.81804101 0.63301685 0.3113321 ]
  [0.62802018 0.58774163 0.67233912 0.33126843 0.71043965]
  [0.45141267 0.76188977 0.36204873 0.97148286 0.17943352]]

 [[0.99350838 0.97780283 0.41807611 0.70134661 0.31880133]
  [0.00668626 0.17747332 0.42988956 0.09231841 0.68793491]
  [0.82369076 0.5235708  0.82605785 0.47252804 0.1333593 ]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [5]:
### [your code here]
#b = np.ones((5,2,3) ,dtype=int) the  first way
b = np.ones((5,2,3))



### 6. Print b.


In [6]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [7]:
### [your code here]
    
    
if a.size == b.size:
       print ("same")
else:
       print("different")


same



### 8. Are you able to add a and b? Why or why not?


In [8]:
### [your code here]
#if a and b have different shape i can't
if a.shape == b.shape:
        print ("same")
else:
         print("different") 

different




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [9]:
### [your code here]
c=np.transpose(b,(1,2,0))


### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [10]:
### [your code here]
d=a+c
print("shap of a",a.shape)
print("shap of c",c.shape)
print("shap of d",d.shape)



shap of a (2, 3, 5)
shap of c (2, 3, 5)
shap of d (2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [12]:
### [your code here]
print("Array a", a)
print("\nArray d", d)
#d is just a shifted by +1 because c is filled with ones.


Array a [[[0.68495333 0.92562567 0.81804101 0.63301685 0.3113321 ]
  [0.62802018 0.58774163 0.67233912 0.33126843 0.71043965]
  [0.45141267 0.76188977 0.36204873 0.97148286 0.17943352]]

 [[0.99350838 0.97780283 0.41807611 0.70134661 0.31880133]
  [0.00668626 0.17747332 0.42988956 0.09231841 0.68793491]
  [0.82369076 0.5235708  0.82605785 0.47252804 0.1333593 ]]]

Array d [[[1.68495333 1.92562567 1.81804101 1.63301685 1.3113321 ]
  [1.62802018 1.58774163 1.67233912 1.33126843 1.71043965]
  [1.45141267 1.76188977 1.36204873 1.97148286 1.17943352]]

 [[1.99350838 1.97780283 1.41807611 1.70134661 1.31880133]
  [1.00668626 1.17747332 1.42988956 1.09231841 1.68793491]
  [1.82369076 1.5235708  1.82605785 1.47252804 1.1333593 ]]]



### 12. Multiply a and c. Assign the result to e.


In [13]:
### [your code here]
e=a*c



### 13. Does e equal to a? Why or why not?


In [109]:
### [your code here]
## yes e is equal to a because multiplying by 1 doe not change value
print(e==a)
print ("yes e==a")

[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]
yes e==a




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [14]:
### [your code here]
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max)
print(d_min)
print(d_mean)

1.9935083755554932
1.0066862611139862
1.553736333068892



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [15]:
### [your code here]
f= np.empty((2,3,5))
print (f)

[[[1.68495333 1.92562567 1.81804101 1.63301685 1.3113321 ]
  [1.62802018 1.58774163 1.67233912 1.33126843 1.71043965]
  [1.45141267 1.76188977 1.36204873 1.97148286 1.17943352]]

 [[1.99350838 1.97780283 1.41807611 1.70134661 1.31880133]
  [1.00668626 1.17747332 1.42988956 1.09231841 1.68793491]
  [1.82369076 1.5235708  1.82605785 1.47252804 1.1333593 ]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [16]:

print(len(d.flat))


for X in range (0,len(d.flat)):
    if (d_mean<d.flat[X]) and (d.flat[X] < d_max):
   
        f.flat[X]=75
    
    if d_min <  d.flat[X] < d_mean: 
        f.flat[X]=25
    
    if  d.flat[X]==d_mean:
  
        f.flat[X] =50
    

    if  d.flat[X] == d_min:
        f.flat=00 
    if d.flat[X] < d_max:
        f.flat[X]==100
print(f)



30
[[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0. 25. 25. 25. 75.]
  [75. 25. 75. 25. 25.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [17]:
### [your code here]
print("d",d)
print("f",f)

d [[[1.68495333 1.92562567 1.81804101 1.63301685 1.3113321 ]
  [1.62802018 1.58774163 1.67233912 1.33126843 1.71043965]
  [1.45141267 1.76188977 1.36204873 1.97148286 1.17943352]]

 [[1.99350838 1.97780283 1.41807611 1.70134661 1.31880133]
  [1.00668626 1.17747332 1.42988956 1.09231841 1.68793491]
  [1.82369076 1.5235708  1.82605785 1.47252804 1.1333593 ]]]
f [[[ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.]
  [ 0. 25. 25. 25. 75.]
  [75. 25. 75. 25. 25.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.